version: '2'
services:
    rfbroyalty-app:
        image: rfbroyalty
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://rfbroyalty-mysql:3306/rfbroyalty?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    rfbroyalty-mysql:
        extends:
            file: mysql.yml
            service: rfbroyalty-mysql
